import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from './Component/Footer/Footer'
import Header from './Component/Header/Header'
import MyBlog from './Component/MyBlog'
import Image3 from '../assets/images/react.png'
import MyIndex from './MyIndex'
import AddPost from './Component/post/AddPost'

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <div className='light-theme'>
    //     <Header />
    //     <div className="hero">

    //       <div className="container">

    //         <div className="left">

    //           <h1 className="h1">
    //             Hi, I'm <b>Preet&nbsp;Patel</b>.
    //             <br />Web Developer
    //           </h1>

    //           <p className="h3">
    //             Specialized in <abbr title="Accessibility">React.js and Next.js </abbr>
    //             and Core Web Vitals
    //           </p>

    //           <div className="btn-group">
    //             <a href="#" className="btn btn-primary">Contact Me</a>
    //             <a href="#" className="btn btn-secondary">About Me</a>
    //           </div>

    //         </div>

    //         <div className="right">

    //           <div className="pattern-bg"></div>
    //           <div className="img-box">
    //             {/* <img src="./assets/images/hero.png" alt="Julia Walker" className="hero-img" /> */}
    //             <Image
    //               src={Image3}
    //               alt="Logo"

    //               layout="intrinsic"
    //               className="hero-img"
    //             />
    //             <div className="shape shape-1"></div>
    //             <div className="shape shape-2"></div>
    //           </div>

    //         </div>

    //       </div>

    //     </div>
    //     <MyBlog />
    //     <Footer />
    //   </div>

    // </div>
    <>
    {/* <MyIndex /> */}
    <AddPost/>
    </>
  )
}

export default Home
